name: "email_sender_workflow"

on:
    push:
        branches:
            - master

jobs:
    send_email:
        runs-on: ubuntu-latest
        steps:
            - name: "Checkout Code"
              uses: actions/checkout@v2

            - name: "Setup Python"
              uses: actions/setup-python@v2
              with:
                python-version: '3.x'

            - name: "Install Dependencies"
              run: | 
                 python -m pip install --upgrade pip
                 pip install smtplib email

            - name: "Send mail by executing python script"
              run: python script.py
              env:
                WORKFLOW_NAME: ${{ github.workflow }}
                REPO_NAME: ${{ github.repository }}
                WORKFLOW_RUN_ID: ${{ github.run_id}}
                SENDER_PASSWORD: ${{ secrets.Sender_Password }}
                SENDER_EMAIL: ${{ secrets.Sender_Email }}
                RECIEVER_EMAIL: ${{ secrets.Receiver_Email }}
